AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Description: S3 bucket where the CloudFormation templates are
    Type: String

Resources:
  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.amazonaws.com/roles.yaml
  DataPointTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.amazonaws.com/dynamodb.yaml
