AWSTemplateFormatVersion: '2010-09-09'

Resources:
  GetDataLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used by the HTTP API endpoint lambda
      RoleName: get-data-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: get-data-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: arn:aws:dynamodb:eu-north-1:237937621781:table/DataPoints
  ScheduledLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used by the scheduled update lambda
      RoleName: scheduled-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: scheduled-lambda-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: arn:aws:dynamodb:eu-north-1:237937621781:table/DataPoints
